image: registry.gitlab.salondev.net/kuber-infra/k8s-deploy
variables:
  CI_API_TOKEN: '8d50e3627e741aeb3aff1447cab83989ecdc6a0a'
  CI_OWNER_NAME: 'SalonUltimate'
  CI_APP_NAME: 'POS'

stages:
  - build
  - beta

build:
  stage: build
  script:
    - ./ci/gitlab.sh
  only:
    - master
  tags:
    - docker


beta:on-schedule:
  stage: beta
  only:
    - schedules
  tags:
    - docker
  script:
    - fastlane beta