image: registry.gitlab.salondev.net/mobile/appcenter:latest
variables:
  AC_API_TOKEN: '8d50e3627e741aeb3aff1447cab83989ecdc6a0a'
  AC_OWNER_NAME: 'SalonUltimate'
  AC_APP_NAME: 'POS'
  MIRROR_PATH: 'salonultimate/pos.git'

stages:
  - build

build:
  stage: build
  script:
    - . sync_gitlab
    - . sync_appcenter
  tags:
    - docker