stages:
  - build
  - archive

build_project:
  stage: build
  script:
    - cd ./ios
    - pod install
  tags:
    - iOS

archive_project:
  stage: archive
  script:
    - cd ./ios
    - pod install
  tags:
    - iOS