stages:
  - build
  - beta
  # - archive

build_project:
  stage: build
  except:
    - schedules
  script:
    - npm install
    - cd ./ios && pod install
    - xcodebuild -workspace SalonUltimateRN.xcworkspace -scheme SalonUltimateRN build 
  tags:
    - iOS

# archive_project:
#   stage: archive
#   except:
#     - schedules
#   script:
#     - cd ./ios
#     - pod install
#   tags:
#     - iOS
    
beta:on-schedule:
  stage: beta
  only:
    - schedules
  tags:
    - iOS
  script:
    - fastlane beta