stages:
  - build
  - archive

build_project:
  stage: build
  except:
    - schedules
  script:
    - cd ./ios
    - pod install
  tags:
    - iOS

archive_project:
  stage: archive
  except:
    - schedules
  script:
    - cd ./ios
    - pod install
  tags:
    - iOS
    
beta:on-schedule:
  only:
    - schedules
  script:
    - brew install fastlane
    - fastlane beta