export default {
  panelTop: {
    backgroundColor: '#FFFFFF',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.30,
    shadowRadius: 3,
    paddingBottom: 18,
    borderBottomColor: '#CACBCF',
    borderBottomWidth: 1 / 2,
  },
  panelTopIcon: {
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 13,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    zIndex: 999,
  },
  topIcon: {
    height: 5,
    width: 36,
    opacity: 0.2,
    borderRadius: 5 / 2,
    backgroundColor: '#000000',
  },
  panelTopLine: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-start',
    backgroundColor: 'transparent',
    width: '90%',
  },
  slidePanel: {
    position: 'absolute',
    flex: 1,
    justifyContent: 'center',
  },
  slidePanelWrapper: {
    height: 50,
    paddingTop: 10,
    width: '100%',
    paddingLeft: 15,
    paddingRight: 15,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  swipablePanelIconLeft: {
    marginBottom: 15,
  },
  barsIcon: {
    fontSize: 20,
    color: 'rgb(114.75, 122.4, 142.8)',
  },
  swipablePanelIconRight: {
    marginBottom: 25,
  },
  topBorder: {
    width: '100%',
    height: 1,
    borderTopWidth: 1,
    borderTopColor: 'rgb(114.75, 122.4, 142.8)',
    marginTop: 40,
  },
  headerPanelWithSlider: {
    paddingTop: 10,
  },
  panelContainer: {
    backgroundColor: '#FFFFFF',
    flexDirection: 'column',
    width: '100%',
    flex: 1,
  },
  panelIcons: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '90%',
    height: 105,
  },
  panelMiddle: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    miHeight: 200,
    borderBottomColor: '#CACBCF',
    borderBottomWidth: 1 / 2,
  },
  auditContainer: {
    flex: 1,
    alignSelf: 'stretch',
    alignItems: 'center',
  },
  panelDiff: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 160,
  },
};
