import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#00000040',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    zIndex: 99999,
  },
  bodyContainer: {
    borderRadius: 10,
    minHeight: 243,
    width: 270,
    backgroundColor: '#FFFFFF',
  },
  header: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    minHeight: 50,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
  },
  footer: {
    height: 50,
    borderTopColor: '#3F3F3F',
    borderTopWidth: StyleSheet.hairlineWidth / 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    marginTop: 10,
  },
  rightBorder: {
    borderRightColor: '#3F3F3F',
    borderRightWidth: StyleSheet.hairlineWidth / 2,
  },
  body: {
    backgroundColor: '#fff',
    paddingHorizontal: 17,
    height: 133,
  },
  textArea: {
    height: 123,
    paddingVertical: 5,
    paddingRight: 5,
  },
  textAreaContainer: {
    borderColor: '#8E8E93',
    borderWidth: StyleSheet.hairlineWidth / 2,
    paddingHorizontal: 5,
  },
  title: {
    fontSize: 17,
    lineHeight: 22,
    color: '#115ECD',
    fontFamily: 'Roboto',
    paddingHorizontal: 5,
    marginTop: 10,
    marginBottom: 10,
  },
  titleWithDescription: {
    marginBottom: 5,
  },
  description: {
    fontSize: 13,
    lineHeight: 22,
    color: '#110A24',
    fontFamily: 'Roboto',
    paddingHorizontal: 2,
    textAlign: 'center',
    marginBottom: 10,
  },
  footerButton: {
    flex: 1,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  textCancel: {
    fontSize: 17,
    lineHeight: 22,
    color: '#4D5067',
    fontFamily: 'Roboto-Medium',
  },
  textOk: {
    fontSize: 17,
    lineHeight: 22,
    color: '#115ECD',
    fontFamily: 'Roboto-Medium',
  },
});
