const tintColor = '#2f95dc';

export default {
  tintColor,
  doneButtonDisabled: 'rgba(0,0,0,0.3)',
  white: '#FFFFFF',
  tabIconDefault: '#ccc',
  tabIconSelected: tintColor,
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#FFFFFF',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: tintColor,
  noticeText: '#FFFFFF',
  defaultGrey: '#727A8F',
  defaultRed: '#D1242A',
  defaultBlack: '#110A24',
  defaultBlue: '#115ECD',
  defaultOrange: '#F5A623',
  lightGrey: '#F1F1F1',
  mediumGrey: '#C0C0C0',
  heavyGrey: '#86868A',
  gray90: '#E5E5E5',
  mediumBlue: '#DDE6F4',
  lightBlue: '#F3F7FC',
  lightBlueBorder: '#F4F7FC',
  secondaryLightBlue: '#1B65CF',
  secondaryBlack: '#2F3142',
  conflictBox: '#FFF7CC',
  darkBlue: '#0C4699',
  selectedGreen: '#1DBF12',
  dividerGrey: '#0C4699',
  divider: '#C0C1C6',
  searchBarBackground: '#D9D9DA',
  noContentBackground: '#F4F4F4',
};
