export default {
  panelTopLine: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-start',
    backgroundColor: 'transparent',
    width: '90%',
  },
  panelTopLineLeft: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: 'transparent',
    flex: 1,
  },
  panelTopName: {
    color: '#111415',
    fontSize: 16,
    paddingTop: 2,
    fontFamily: 'Roboto-Medium',
    backgroundColor: 'transparent',
  },
  panelTopService: {
    color: '#111415',
    fontSize: 12,
    lineHeight: 14,
    fontFamily: 'Roboto',
    backgroundColor: 'transparent',
  },
  panelTopRemarksTitle: {
    color: '#727A8F',
    fontSize: 12,
    fontFamily: 'Roboto',
    backgroundColor: 'transparent',
  },
  panelTopRemarks: {
    flex: 1,
    textAlign: 'justify',
    color: '#110A24',
    fontSize: 11,
    fontFamily: 'Roboto',
    backgroundColor: 'transparent',
  },
  containerForBadges: {
    flexDirection: 'row',
    marginLeft: -5,
    marginRight: 5,
    paddingTop: 2,
  },
};
