# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SalonUltimateRN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SalonUltimateRN

  pod 'Fabric'
  pod 'Crashlytics'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge',
    'DevSupport',
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'Core',
    'RCTWebSocket',
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'Picker', :path => '../node_modules/react-native-picker'

  target 'SalonUltimateRNTests' do
    inherit! :search_paths
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'yoga'
        target.build_configurations.each do |config|
          config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
          config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
        end
      end
    end
  end

end
