import {
  StyleSheet,
} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  backgroundImage: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
    top: 0,
  },
  tabLabel: {
    color: 'white',
    fontFamily: 'OpenSans-Regular',
    fontSize: 14,
    paddingBottom: 6,
  },
  textWalkInBtn: {
    color: '#fff',
    fontFamily: 'OpenSans-Regular',
    fontSize: 14,
    textAlign: 'center',
    fontWeight: '600',
    marginTop: 5,
  },
  walkOutRoot: {
    bottom: 138,
  },
  walkoutContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  walkoutImageContainer: {
    height: 100,
    width: 100,
    backgroundColor: '#67A3C7',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 50,
    paddingRight: 8,
    marginBottom: 20,
  },
  walkoutImage: {
    height: 27,
    overflow: 'visible',
  },
  walkoutText: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 22,
    color: '#3D3C3B',
  },
  walkoutTextBold: {
    fontFamily: 'OpenSans-Bold',
    fontSize: 22,
    color: '#3D3C3B',
  },
  walkoutInput: {
    color: '#3D3C3B',
    height: 120,
    borderColor: 'rgba(10,39,74,0.2)',
    borderWidth: 1,
    marginTop: 20,
    flex: 1,
    marginLeft: 20,
    marginRight: 20,
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
  },
  walkoutPlaceholder: {
    fontStyle: 'italic',
  },
  walkoutTextContainer: {
    flexDirection: 'row',
  },
  walkoutButtonContainer: {
    flexDirection: 'row',
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
  },
  walkoutButtonOk: {
    backgroundColor: '#67A3C7',
    flex: 1,
    height: 60,
    borderRadius: 80,
    marginLeft: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#67A3C7',
  },
  walkoutButtonCancel: {
    backgroundColor: '#fff',
    flex: 1,
    height: 60,
    borderRadius: 80,
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#67A3C7',
  },
  walkoutTextOk: {
    color: '#fff',
    fontSize: 18,
    fontFamily: 'OpenSans-Regular',
  },
  walkoutTextCancel: {
    color: '#67A3C7',
    fontSize: 18,
    fontFamily: 'OpenSans-Regular',
  },
  walkinButton: {
    position: 'absolute',
    right: 10,
    top: 0,
    width: 92,
    borderWidth: 1,
    borderColor: '#1DBF12',
    borderRadius: 16,
    backgroundColor: '#1DBF12',
    height: 33,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.6,
    shadowRadius: 1,
    flexDirection: 'row',
  },
  walkinButtonText: {
    fontFamily: 'Roboto-Medium',
    fontSize: 12,
    color: 'white',
  },
  walkinButtonIcon: {
    fontSize: 16,
    marginLeft: 8,
  },
  indicator: {
    borderWidth: 1,
    borderColor: 'white',
    borderRadius: 15.5,
    backgroundColor: 'white',
    height: 31,
    shadowColor: '#000',
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.6,
    shadowRadius: 1,
  },
  tab: {
    height: 31,
    // backgroundColor: 'rgba(0,255,0,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    // alignItems: 'flex-start',
    paddingLeft: 0,
  },
  tabContainer: {
    height: 32,
    borderWidth: 1,
    borderColor: 'rgba(8,46,102,0.5)',
    borderRadius: 16,
    backgroundColor: '#115ECD',
    marginBottom: 9,
  },
  tabQueueCounter: {
    backgroundColor: '#C3D6F1',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'transparent',
    // paddingHorizontal: 3,
    paddingVertical: 0,
    paddingHorizontal: 5,
    marginRight: 5,
  },
  tabQueueCounterText: {
    color: '#1963CE',
    fontSize: 10,
    fontFamily: 'Roboto-Regular',
    padding: 0,
  },
  tabLabelContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 1,
    flexDirection: 'row',
    // backgroundColor: 'yellow',
    alignSelf: 'flex-start',
    marginLeft: 15,
    paddingLeft: 0,
    top: -1,
  },
  summaryBar: {
    height: 31,
    backgroundColor: '#0C4699',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  summaryBarTextLeft: {
    color: 'rgba(195,214,242,1)',
    fontSize: 8,
    fontFamily: 'Roboto-Regular',
    marginLeft: 16,
  },
  summaryBarTextLeftEm: {
    fontSize: 10,
    fontWeight: '500',
  },
  summaryBarTextRight: {
    color: 'white',
    fontSize: 10,
    fontFamily: 'Roboto-Regular',
    marginRight: 23,
  },
  summaryBarTextRightEm: {
    fontFamily: 'Roboto-Bold',
    fontSize: 11,
  },
  searchTypeContainer: {
    backgroundColor: '#115ECD',
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
  },
  searchType: {
    marginHorizontal: 16,
    marginTop: 7,
    marginBottom: 9,
    height: 27,
    flexDirection: 'row',
    borderRadius: 4,
    borderColor: 'white',
    borderWidth: 1,
  },
  searchTypeText: {
    fontSize: 13,
    fontWeight: '500',
    fontFamily: 'Roboto-Regular',
    color: 'white',
  },
  searchClient: {
    borderTopLeftRadius: 2,
    borderBottomLeftRadius: 2,
    borderColor: 'transparent',
    borderWidth: 2,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchProvider: {
    borderTopRightRadius: 2,
    borderBottomRightRadius: 2,
    borderColor: 'transparent',
    borderWidth: 2,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchEmpty: {
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    padding: 60,
  },
  searchEmptyText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#727A8F',
    fontFamily: 'Roboto-Regular',
    marginVertical: 20,
  },
  searchEmptyTextSmall: {
    fontSize: 11,
    color: '#727A8F',
    fontFamily: 'Roboto-Regular',
  },
  searchEmptyIcon: {
    fontSize: 50,
    // color: '#E3E4E5',
  },
  searchEmptyIconContainer: {
    width: 100,
    height: 100,
    borderWidth: 6,
    borderRadius: 50,
    borderColor: '#E3E4E5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  leftButtonText: {
    color: '#fff',
    fontSize: 14,
    fontFamily: 'Roboto',
  },
  backIcon: {
    fontSize: 30,
    color: '#fff',
    marginRight: 8,
  },
  backContainer: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  animateText: {
    fontFamily: 'Roboto-Medium',
    fontSize: 12,
  },
  notFoundText: { color: 'black' },
  tabViewStyle: {
    flex: 1,
    backgroundColor: '#115ECD',
    borderWidth: 0,
  },
});
