import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  scrollContainer: {
    flex: 1,
  },
  scrollContentContainer: {
    alignItems: 'center',
  },
  container: {
    flex: 1,
    backgroundColor: 'rgb(17.85, 94.35, 204)',
  },
  inputContainer: {
    // width: 292,
    flexDirection: 'row',
    marginLeft: 'auto',
    marginRight: 'auto',
    paddingLeft: 20,
    paddingRight: 20,
    marginBottom: 30,
    justifyContent: 'center',
  },
  item: {
    flex: 1,
    maxWidth: 260,
    marginLeft: 18,
    marginTop: 0,
    paddingTop: 0,
  },
  inputLabel: {
    color: 'white',
    fontFamily: 'OpenSans-Regular',
  },
  input: {
    color: 'white',
    fontSize: 16,
    fontFamily: 'OpenSans-Regular',
    paddingTop: 0,
    marginTop: 0,
    paddingLeft: 0,
  },
  inputIcon: {
    width: 28,
    height: 28,
    alignSelf: 'flex-end',
    resizeMode: 'contain',
  },
  logo: {
    marginTop: 80,
    marginLeft: 'auto',
    marginRight: 'auto',
    marginBottom: 37,
    height: 72,
    width: 72,
  },
  loginButton: {
    width: 250,
    height: 65,
    marginTop: 17,
    marginBottom: 18,
    alignSelf: 'center',
    backgroundColor: 'white',
    borderColor: 'white',
    alignItems: 'center',
  },
  loginButtonText: {
    color: 'rgba(48,120,164,1)',
    fontSize: 18,
    fontFamily: 'OpenSans-Regular',
    textAlign: 'center',
    marginLeft: 'auto',
    marginRight: 'auto',
    letterSpacing: 2,
  },
  touchIdButton: {
    width: 250,
    height: 50,
    marginTop: 62,
    alignSelf: 'center',
    backgroundColor: 'transparent',
    borderColor: 'white',
    alignItems: 'center',
  },
  touchIdButtonText: {
    color: 'white',
    fontSize: 18,
    fontFamily: 'OpenSans-Regular',
    textAlign: 'center',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  footer: {
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: 60,
    marginBottom: 20,
    borderTopColor: '#eee',
    borderTopWidth: 1,
    paddingTop: 20,
    paddingHorizontal: 20,
    height: 80,
  },
  bodyText: {
    color: 'white',
    fontSize: 14,
    fontFamily: 'OpenSans-Regular',
    backgroundColor: 'transparent',
  },
  footerText: {
    color: 'rgba(103,163,199,1)',
    fontSize: 14,
    fontFamily: 'OpenSans-Regular',
    backgroundColor: 'transparent',
  },
  bodyLink: {
    color: 'white',
    textDecorationLine: 'underline',
    fontFamily: 'OpenSans-Bold',
  },
  fingerprintModalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.2)',
    justifyContent: 'center',
  },
  fingerprintModal: {
    backgroundColor: 'white',
    borderRadius: 6,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fingerprintImage: {
    width: 130,
    height: 130,
    marginTop: 40,
  },
  fingerprintText: {
    fontSize: 22,
    fontFamily: 'OpenSans-Regular',
    color: 'rgba(10,39,74,1)',
    textAlign: 'center',
    width: 300,
    marginTop: 41,
    paddingLeft: 10,
    paddingRight: 10,
  },
  fingerprintAccept: {
    backgroundColor: 'rgba(103,163,199,1)',
    width: 220,
    height: 58,
    marginTop: 52,
    borderColor: 'white',
    alignSelf: 'center',
  },
  fingerprintAcceptText: {
    fontSize: 18,
    fontFamily: 'OpenSans-Regular',
    color: 'white',
    textAlign: 'center',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  fingerprintDeny: {
    width: 220,
    height: 58,
    marginTop: 27,
    marginBottom: 30,
    alignSelf: 'center',
  },
  fingerprintDenyText: {
    fontSize: 18,
    fontFamily: 'OpenSans-Regular',
    color: 'rgba(107,103,99,1)',
    textDecorationLine: 'underline',
    textAlign: 'center',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  errorMessage: {
    color: 'red',
    fontSize: 14,
    fontFamily: 'OpenSans-Regular',
    backgroundColor: 'white',
    padding: 10,
    borderRadius: 8,
    borderColor: 'white',
  },
});
