import { StyleSheet } from 'react-native';
import { ifIphoneX } from 'react-native-iphone-x-helper';
import Colors from '../../constants/Colors';

const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#00000040',
    justifyContent: 'flex-end',
    flex: 1,
    height: '100%',
  },
  header: {
    backgroundColor: Colors.defaultBlue,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    height: 40,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  body: {
    padding: 15,
    ...ifIphoneX(
      {
        paddingBottom: 30,
      },
      {},
    ),
  },
  dateText: {
    fontFamily: 'Roboto-Medium',
    fontSize: 16,
    marginBottom: 30 - 16,
    color: Colors.defaultBlack,
  },
  placeholderText: {
    fontSize: 14,
    color: Colors.defaultGrey,
    lineHeight: 22,
  },
  middleSectionDivider: {
    width: '95%',
    height: 1,
    alignSelf: 'center',
    backgroundColor: Colors.mediumBlue,
  },
  otherOptionsBtn: {
    height: 67,
    paddingRight: 0,
  },
  subIcon: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.gray90,
  },
  iconContainer: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: Colors.gray90,
    backgroundColor: Colors.gray90,
    justifyContent: 'center',
    alignItems: 'center',
  },
  otherOptionsLabels: {
    color: Colors.defaultBlue,
  },
  clockIconContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  penIconContainer: {
    position: 'absolute',
    backgroundColor: 'transparent',
    paddingTop: 5,
  },
  banIconContainer: {
    position: 'absolute',
    paddingTop: 10,
    paddingRight: 12,
    backgroundColor: 'transparent',
  },
  bookApptContainer: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  slideContainer: {
    backgroundColor: 'white',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  buttonContainer: {
    height: 48,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderRadius: 5,
    borderColor: Colors.defaultBlue,
    backgroundColor: Colors.defaultBlue,
  },
  buttonText: {
    fontSize: 12,
    color: 'white',
    fontFamily: 'Roboto-Bold',
  },
  addonsContainer: {
    marginHorizontal: 2,
    backgroundColor: Colors.lightGrey,
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 4,
    paddingBottom: 9,
    paddingHorizontal: 8,
  },
  addonsTitleText: {
    fontSize: 9,
    lineHeight: 22,
    color: Colors.defaultGrey,
  },
  addonsInputContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    borderBottomColor: 'transparent',
    borderTopColor: 'transparent',
    borderColor: Colors.lightBlue,
    borderWidth: 1,
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 1,
    zIndex: 2,
    shadowOffset: { width: 0, height: 2 },
    backgroundColor: Colors.lightBlue,
  },
  addonInput: {
    height: 39,
    flexDirection: 'row',
    paddingLeft: 11,
    paddingRight: 6,
  },
  addonInputInner: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  addonIconButton: {
    padding: 10,
  },
  addonIcon: {
    marginRight: 10,
    transform: [{ rotate: '90deg' }],
  },
  addonInputText: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.defaultBlack,
  },
  addonCount: {
    height: 24,
    borderRadius: 12,
    backgroundColor: 'white',
    padding: 5,
    marginLeft: 10,
  },
  addonCountText: {
    fontSize: 12,
    color: Colors.defaultBlue,
    fontFamily: 'Roboto-Bold',
  },
  addonRequiredText: {
    fontSize: 10,
    lineHeight: 22,
    color: '#F5A623',
    marginLeft: 10,
    fontFamily: 'Roboto-Medium',
  },
  addonIconContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  addonLengthText: {
    fontSize: 12,
    lineHeight: 18,
    fontFamily: 'Roboto-Medium',
    color: Colors.defaultGrey,
    opacity: 0.9,
    marginRight: 10,
  },
  conflictBox: {
    alignSelf: 'stretch',
    backgroundColor: Colors.conflictBox,
    borderRadius: 4,
    marginVertical: 8,
    flexDirection: 'row',
    paddingHorizontal: 12,
    height: 32,
    alignItems: 'center',
  },
  conflictBoxInner: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  conflictBoxTitleText: {
    color: Colors.secondaryBlack,
    fontSize: 11,
    lineHeight: 22,
    marginLeft: 7,
  },
  conflictBoxShowText: {
    fontSize: 11,
    lineHeight: 22,
    color: Colors.defaultRed,
    textDecorationLine: 'underline',
  },
  flexStart: {
    justifyContent: 'flex-start',
  },
  flexColumn: {
    flexDirection: 'column',
  },
  mainInputGroup: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    borderBottomColor: 'transparent',
    borderTopColor: 'transparent',
    borderColor: Colors.lightBlueBorder,
    borderWidth: 1,
    marginTop: 15,
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 1,
    zIndex: 2,
    shadowOffset: { width: 0, height: 2 },
    backgroundColor: Colors.lightBlue,
  },
  inputHeight: {
    height: 39,
  },
  inputColor: {
    color: Colors.defaultBlue,
  },
  requestedContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 15,
  },
  requestedText: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.defaultBlack,
  },
  lengthContainer: {
    marginVertical: 14,
    backgroundColor: Colors.lightGrey,
    height: 32,
    borderRadius: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 12,
  },
  lengthText: {
    fontSize: 13,
    lineHeight: 22,
    color: Colors.secondaryBlack,
    marginRight: 6,
  },
  serviceLengthText: {
    fontSize: 13,
    lineHeight: 22,
    color: '#2F3142',
    opacity: 1,
    fontStyle: 'normal',
  },
  buttonGroupContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
  },
  backDrop: {
    backgroundColor: 'transparent',
    position: 'absolute',
    bottom: 0,
    right: 0,
    left: 0,
  },
  cancelButton: {
    flex: 1,
    justifyContent: 'flex-start',
  },
  cancelButtonText: {
    color: 'white',
    fontSize: 14,
    lineHeight: 18,
    fontFamily: 'Roboto-Medium',
    textAlign: 'left',
  },
  headerMiddle: {
    flex: 2,
    maxWidth: '50%',
    justifyContent: 'center',
    alignItems: 'stretch',
  },
  headerStub: {
    flex: 1,
  },
  justifyCenter: {
    justifyContent: 'center',
  },
  serviceLengthStyle: {
    fontStyle: 'italic',
  },
  contentStyle: {
    alignItems: 'flex-start',
    paddingLeft: 11,
  },
});
export default styles;
