export const STORE_FORM = 'STORE_FORM';
export const PURGE_FORM = 'PURGE_FORM';
export const FETCH_FORM = 'FETCH_FORM';

export const EMPLOYEES = 'EMPLOYEES';
export const EMPLOYEES_RECEIVED = 'EMPLOYEES_RECEIVED';
export const EMPLOYEES_FAILED = 'EMPLOYEES_FAILED';

export const SETTINGS_BY_NAME_RECEIVED = 'SETTINGS_BY_NAME_RECEIVED';
export const SETTINGS_BY_NAME_FAILED = 'SETTINGS_BY_NAME_FAILED';
