// queue constants from webend redux
export const QUEUE = 'QUEUE';
export const QUEUE_RECEIVED = 'QUEUE_RECEIVED';
export const QUEUE_FAILED = 'QUEUE_FAILED';
export const QUEUE_UPDATE_ITEM = 'QUEUE_UPDATE_ITEM';
export const QUEUE_DELETE_ITEM = 'QUEUE_DELETE_ITEM';

export const STORE_FORM = 'STORE_FORM';
export const PURGE_FORM = 'PURGE_FORM';
export const FETCH_FORM = 'FETCH_FORM';

export const EMPLOYEES = 'EMPLOYEES';
export const EMPLOYEES_RECEIVED = 'EMPLOYEES_RECEIVED';
export const EMPLOYEES_FAILED = 'EMPLOYEES_FAILED';

export const CLIENT_CHECKED_IN = 'CLIENT_CHECKED_IN';
export const CLIENT_CHECKED_IN_FAILED = 'CLIENT_CHECKED_IN_FAILED';
export const CLIENT_CHECKED_IN_RECEIVED = 'CLIENT_CHECKED_IN_RECEIVED';

export const CLIENT_NO_SHOW = 'CLIENT_NO_SHOW';
export const CLIENT_NO_SHOW_RECEIVED = 'CLIENT_NO_SHOW_RECEIVED';
export const CLIENT_NO_SHOW_FAILED = 'CLIENT_NO_SHOW_FAILED';

export const CLIENT_RETURNED_LATER = 'CLIENT_RETURNED_LATER';
export const CLIENT_RETURNED_LATER_FAILED = 'CLIENT_RETURNED_LATER_FAILED';
export const CLIENT_RETURNED_LATER_RECEIVED = 'CLIENT_RETURNED_LATER_RECEIVED';

export const CLIENT_RETURNED = 'CLIENT_RETURNED';
export const CLIENT_RETURNED_RECEIVED = 'CLIENT_RETURNED_RECEIVED';
export const CLIENT_RETURNED_FAILED = 'CLIENT_RETURNED_FAILED';

export const CLIENT_WALKED_OUT = 'CLIENT_WALKED_OUT';
export const CLIENT_START_SERVICE = 'CLIENT_START_SERVICE';

export const CLIENT_FINISH_SERVICE = 'CLIENT_FINISH_SERVICE';
export const CLIENT_FINISH_SERVICE_FAILED = 'CLIENT_FINISH_SERVICE_FAILED';
export const CLIENT_FINISH_SERVICE_RECEIVED = 'CLIENT_FINISH_SERVICE_RECEIVED';

export const CLIENT_UNDOFINISH_SERVICE = 'CLIENT_UNDOFINISH_SERVICE';
export const CLIENT_UNDOFINISH_SERVICE_FAILED = 'CLIENT_UNDOFINISH_SERVICE_FAILED';
export const CLIENT_UNDOFINISH_SERVICE_RECEIVED = 'CLIENT_UNDOFINISH_SERVICE_RECEIVED';

export const CLIENT_TO_WAITING = 'CLIENT_TO_WAITING';
export const CLIENT_TO_WAITING_RECEIVED = 'CLIENT_TO_WAITING_RECEIVED';
export const CLIENT_TO_WAITING_FAILED = 'CLIENT_TO_WAITING_FAILED';

export const ROW_EXPANDED = 'ROW_EXPANDED';

export const TIME_UPDATE = 'TIME_UPDATE';

export const ACTIVE_VIEW_UPDATE = 'ACTIVE_VIEW_UPDATE';

export const START_COMBINE = 'START_COMBINE';
export const CANCEL_COMBINE = 'CANCEL_COMBINE';
export const FINISH_COMBINE = 'FINISH_COMBINE';
export const COMBINE_CLIENT = 'COMBINE_CLIENT';
export const GROUP_LEAD_UPDATE = 'GROUP_LEAD_UPDATE';
export const UNCOMBINE = 'UNCOMBINE';
export const UPDATE_GROUPS = 'UPDATE_GROUPS';

export const SETTINGS_BY_NAME_RECEIVED = 'SETTINGS_BY_NAME_RECEIVED';
export const SETTINGS_BY_NAME_FAILED = 'SETTINGS_BY_NAME_FAILED';

export const PUT_QUEUE = 'PUT_QUEUE';
export const PUT_QUEUE_SUCCESS = 'PUT_QUEUE_SUCCESS';
export const PUT_QUEUE_FAILED = 'PUT_QUEUE_FAILED';

export const GET_QUEUE_STATE = 'GET_QUEUE_STATE';
export const GET_QUEUE_STATE_SUCCESS = 'GET_QUEUE_STATE_SUCCESS';
export const GET_QUEUE_STATE_FAILED = 'GET_QUEUE_STATE_FAILED';
