// queue constants from webend redux
export const QUEUE = 'QUEUE';
export const QUEUE_RECEIVED = 'QUEUE_RECEIVED';
export const QUEUE_FAILED = 'QUEUE_FAILED';

export const EMPLOYEES = 'EMPLOYEES';
export const EMPLOYEES_RECEIVED = 'EMPLOYEES_RECEIVED';
export const EMPLOYEES_FAILED = 'EMPLOYEES_FAILED';

export const CLIENT_CHECKED_IN = 'CLIENT_CHECKED_IN';
export const CLIENT_RETURNED_LATER = 'CLIENT_RETURNED_LATER';
export const CLIENT_WALKED_OUT = 'CLIENT_WALKED_OUT';
export const CLIENT_START_SERVICE = 'CLIENT_START_SERVICE';

export const CLIENT_FINISH_SERVICE = 'CLIENT_FINISH_SERVICE';
export const CLIENT_TO_WAITING = 'CLIENT_TO_WAITING';

export const ROW_EXPANDED = 'ROW_EXPANDED';

export const TIME_UPDATE = 'TIME_UPDATE';

export const ACTIVE_VIEW_UPDATE = 'ACTIVE_VIEW_UPDATE';

export const START_COMBINE = 'START_COMBINE';
export const CANCEL_COMBINE = 'CANCEL_COMBINE';
export const FINISH_COMBINE = 'FINISH_COMBINE';
export const COMBINE_CLIENT = 'COMBINE_CLIENT';
export const GROUP_LEAD_UPDATE = 'GROUP_LEAD_UPDATE';
export const UNCOMBINE = 'UNCOMBINE';
export const UPDATE_GROUPS = 'UPDATE_GROUPS';
