export default {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  FINGERPRINT_ENABLE: 'FINGERPRINT_ENABLE',
  FINGERPRINT_DISABLE: 'FINGERPRINT_DISABLE',
  FINGERPRINT_AUTHENTICATE: 'FINGERPRINT_AUTHENTICATE',
};
